services:
  - type: web
    name: planncomm-backend
    env: node
    buildCommand: cd planncomm-backend && npm install && npm run build
    startCommand: cd planncomm-backend && npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/health
